### PR TITLE
Add pFSep and fix pRSep for AppType.

### PR DESCRIPTION
**Pull request by theunixman**
Maybe don't merge it, but just look at the changes, unless you reset --hard HEAD first.

### CODE REVIEW

**Review by jacqueline-homan — CHANGES_REQUESTED** [review]
This is **exactly the same code that I changed my local version to in order to try to get it to parse correctly right before you put this PR up with the same exact code. But either way, it still doesn't work. At a loss here.

**Review by jacqueline-homan — CHANGES_REQUESTED** [review]
Yup. This was already handled on my end and pushed up just as you were editing this same thing on your PR. Scary how we think alike, isn't it? :)

**Comment by theunixman** [comment]
Ok, here's another version. If you've made changes, push them up and let me remerge before doing any merges there.

**Comment by jacqueline-homan** [comment]
@misandrist I did an updated commit and push of what I had. Re-merge on your end and then resubmit this latest PR so I can merge it w/ master.

**Review by jacqueline-homan — APPROVED** [review]

**Comment by theunixman** [comment]
Ok, I've got the NTE parser working. So there were mainly two issues with it I think:

1. As usual, the field separators aren't consistent.
2. The Notes field (NTE02) is just a string, and nothing else, so we don't need to get too deep into its structure.

I also changed the type of NTE01 to a uint16, since it's a number. But it's also not in the EDI file, so really no one knows what would actually be there. I'll see if I can find some other sample files of this format to test on, too.

**Pull request merged**
